### ISSUE TITLE
Does it also warns about resource request/limit ratio ? 

### ISSUE THREAD

**Issue by monicagangwar** [derailed/popeye#54]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by derailed** [comment]
@monicagangwar Thank you for the report! Not quiet sure what you mean by request/limit ratio?? Could you expand on that? Thank you!

**Comment by monicagangwar** [comment]
@derailed something like resources cpu or memory request to limit ratio is exceeding 0.5
also, utilization/requests warning it shows current utlization, can that be average of certain time ?

**Comment by derailed** [comment]
@monicagangwar Thank you for reporting back! Well, Popeye do report on under/over utilization but at current load which is less than ideal since Popeye does not track metrics. The idea here was you can put load on your cluster and run Popeye to see if you've under/over allocated your resources. I do see some usefulness in checking req/limit and see if they are reasonable and this check could be static regardless of current load. Would this help? So short of taping into prometheus or the likes, Popeye does not track these over time. The idea here was to provide a Popeye option to put load on the cluster and assist the user in checking her resources allocations. Do you think that would be useful? or do you have better ideas?? Totally open for better ways here... Thank you!!
