### ISSUE TITLE
Question: Getting Deprecated API error for ingress.

### ISSUE THREAD

**Issue by collbrain** [derailed/popeye#99]
I am getting following error for ingress, understand that have to change the api but i am running 1.14. Should i changed for that as well ?. Basically, is popeye version aware ?

[POP-403] Deprecated Ingress API group "extensions/v1beta1". Use "networking.k8s.io/v1beta1" instead.

**Comment by derailed** [comment]
@collbrain Popeye is not version aware in the sense that we don't check the cluster version prior to sanitization. Popeye does expect a recent k8s version. Since 1.16 deprecated apis, the sanitizers will report on these deprecation warnings. As a general rule especially in light of CVEs it is a recommended practice to keep your cluster closer to the latest k8s as possible.  Does this make sense?

**Comment by collbrain** [comment]
Is there an older branch that i could pull for 1.13 and 1.14 ?.

The reason is i am running gke cluster, one is 1.14 and prod is 1.13. I don't have permission to upgrade or don't see this getting upgraded in 2-3 months. Meanwhile wanted to check popeye on how it works...

**Comment by derailed** [comment]
@collbrain I don't recall which version of Popeye added the deprecation checks. I think just about the time k8s 1.16 came out. I would recommend staying up with the latest Popeye if you can and lower the deprecation warnings (see spinach.yml) to info until you have a change to upgrade your clusters.
